In [ ]:
import numpy as np

In [ ]:
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy
arr = numpy.array([2,3,4,5,6])
print(arr)

[2 3 4 5 6]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [ ]:
print(np.__version__)

1.25.2


# creating **Array**

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr = np.array(20)
print(arr)

20


In [ ]:
arr = np.array('anjali')
print(arr)

anjali


In [ ]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([[[1,2,3],[6,5,4],[6,7,8]]])
print(arr)

[[[1 2 3]
  [6 5 4]
  [6 7 8]]]


In [ ]:
a = np.array(42)
b = np.array([1,2,3,4])
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)



0
1
2
3


# array indexing

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr[0])

1


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr[4])

5


In [ ]:
arr = np.array([1,2,3,4,5])
print (arr[2] + arr[4])


8


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print('2nd element on 1st row:', arr[0,1])

2nd element on 1st row: 2


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('5th element on 2nd row:', arr[1,4])

5th element on 2nd row: 10


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0,1,2])

6


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('last element from 2nd dim:', arr[1, -1])

last element from 2nd dim: 10


# slicing

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr.dtype)

int64


In [ ]:
arr = np.array(['apple', 'banana', 'mango'])
print(arr.dtype)

<U6


In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
## github


In [ ]:
import numpy as np


In [ ]:
print(np.__version__)


1.25.2


In [ ]:
print(np.__version__)
np.show_config()

1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

# create  a null vector size

In [ ]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
z = np.arange(50)
z = z[::-1]

In [ ]:
z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
z = np.arange(12).reshape(4,3)
print(z)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
a = np.nonzero([1,2,0,0,4,0])
print(a)

(array([0, 1, 4]),)


In [ ]:
z = np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
