In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3],dtype="S")
a

array([b'1', b'2', b'3'], dtype='|S1')

In [ ]:
print(a[2])

b'3'


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
a = ([1,2,3])
print(a[-1:])

[3]


In [ ]:
b = np.array(["Apple","Banana","Cherry"],dtype="S")
b

array([b'Apple', b'Banana', b'Cherry'], dtype='|S6')

In [ ]:
a = np.array([[1,2,3],[4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.shape

(3, 3)

In [ ]:
a.shape[0]

3

In [ ]:
a.shape[1]

3

In [ ]:
a.size

9

In [ ]:
zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
zeros = np.zeros((5,6))
zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
ispace = np.linspace(1,5,12)
ispace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [ ]:
ispace = np.linspace(5,10,8)
ispace

array([ 5.        ,  5.71428571,  6.42857143,  7.14285714,  7.85714286,
        8.57142857,  9.28571429, 10.        ])

In [ ]:
emp = np.empty ((4,6))
emp

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [ ]:
emp_like = np.empty_like(ispace)
emp_like

array([ 5.        ,  5.71428571,  6.42857143,  7.14285714,  7.85714286,
        8.57142857,  9.28571429, 10.        ])

In [ ]:
ide = np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
ide.shape

(45, 45)

In [ ]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr.reshape(3,33)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr = arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr.shape

(99,)

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 1, 0]])
result = arr.sum(axis=0)
print(result)

[12  8  9]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 1, 0]])
result = arr.sum(axis=1)
print(result)

[ 6 15  8]


In [ ]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [ ]:
arr.flat

In [ ]:
for item in arr.flat:
  print(item)

1
2
3
4
5
6
7
1
0


In [ ]:
arr.ndim

2

In [ ]:
arr.size

9

In [ ]:
arr.nbytes

72

In [ ]:
one = np.array([1,3,4,634,2])
one.argmax()

3

In [ ]:
one = np.array([1,3,4,634,2])
one.argmin()

0

In [ ]:
one.argsort()

array([0, 4, 1, 2, 3])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
arr.argmin()

8

In [ ]:
arr.argmax()

6

In [ ]:
arr.argmax(axis = 0)

array([2, 1, 1])

In [ ]:
arr.argmax(axis = 1)

array([2, 2, 0])

In [ ]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [ ]:
arr.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
arr2 = np.array ([[1,2,1],
                  [4,0,6],
                  [8,1,0]])
arr + arr2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [ ]:
arr * arr2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [ ]:
arr.sum()

29

In [ ]:
arr.max()


7

In [ ]:
arr.min()

0

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
np.where(arr > 5)

(array([1, 2]), array([2, 0]))

In [ ]:
np.count_nonzero(arr)

8

In [ ]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [ ]:
arr[1,2] = 0

In [ ]:
type()

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [ ]:
import sys

In [ ]:
py_arr = [0,4,55,2]
np_arr = np.array(py_arr)
sys.getsizeof(1) * len(py_arr)

112

In [ ]:
np_arr.itemsize * np_arr.size

32

In [ ]:
np_arr.tolist()

[0, 4, 55, 2]

In [ ]:
print(np.version)

<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr[2])

3


In [ ]:
arr = np.array ([[1,2,3,4], [5,6,7,8]])
print('secound element in first rows:', arr[0,1])

secound element in first rows: 2


In [ ]:
a = np.array(['apple', 'banana', 'mango'], dtype='U')
a

array(['apple', 'banana', 'mango'], dtype='<U6')

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12], dtype= 'i')
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)

In [ ]:
a = np.array([4.6,3.5,78.09], dtype = 'f')
a

array([ 4.6 ,  3.5 , 78.09], dtype=float32)

In [ ]:
arr = np.array([1,2,3,4,5])
x = arr.copy()

print(x)

[1 2 3 4 5]


In [ ]:
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 45
print(arr)
print(x)

[45  2  3  4  5]
[45  2  3  4  5]


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])

b = a.reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [ ]:
arr = np.array([1,2,3])
for x in arr:
  print(x)

1
2
3


In [ ]:
arr = np.array([[1,2,3], [4,5,6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
arr = np.array([[1,2,3], [4,5,6]])
for  x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
arr = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9


In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1, arr2), axis=1)
arr

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.hstack((arr1, arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.vstack((arr1, arr2))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.dstack((arr1, arr2))
arr

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [ ]:
arr = np.array ([1,2,3,4,5,6])
a =  np. array_split(arr, 4)
a

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [ ]:

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
a = np.array_split(arr, 3)
a

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [ ]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)
newarr

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [ ]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr,3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[13 14 15]
 [16 17 18]]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr,3)
newarr

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
arr = np.array([1,2,3,4,4,5,4,4])
x = np.where(arr == 4)
x

(array([3, 4, 6, 7]),)

In [ ]:
arr = np.array([1,2,3,4,5,6])
x = np.where(arr%2 == 0)
x

(array([1, 3, 5]),)

In [ ]:
arr = np.array([1,2,3,4,5,6])
x = np.where(arr%2 == 1)
x

(array([0, 2, 4]),)

In [ ]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [ ]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 9, side='right')

print(x)

4


In [ ]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [ ]:
arr = np.array([1,2,3,4,5])
x = np.sort(arr)
x

array([1, 2, 3, 4, 5])

In [ ]:
arr = np.array([1,5,0,9])
x = np.sort(arr)
x

array([0, 1, 5, 9])

In [ ]:
arr = np.array(['apple', 'banana', 'mango'])
x = np.sort(arr)
x

array(['apple', 'banana', 'mango'], dtype='<U6')

In [ ]:
arr = np.array(['apple', 'kiwi', 'banana', 'orange'])
x = np.sort(arr)
x

array(['apple', 'banana', 'kiwi', 'orange'], dtype='<U6')

In [ ]:
arr = np.array(['True', 'False', 'True'])
x = np.sort(arr)
x

array(['False', 'True', 'True'], dtype='<U5')

In [ ]:
arr = np.array([[1,0,6],[4,14,2]])
x = np.sort(arr)
x

array([[ 0,  1,  6],
       [ 2,  4, 14]])

In [ ]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)


[41 43]


In [ ]:
arr = np.array([41, 42, 43, 44])

x = [False, True, False, True]

newarr = arr[x]

print(newarr)


[42 44]


In [ ]:
arr = np.array([41,42,43,44])
filter_arr = []
for element in arr:
  if element > 42:
    filter_arr.append(True)
  else:
      filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [ ]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
